# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
name: Nic Le Breuilly
markdown: kramdown
pygments: true
paginate: 10 # pagination basted on number of posts
exclude: ["README.md", 'sass', 'watch.sh', 'style.scss', 'bootstrap.scss'] # files to exclude

